# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vakio Test
version: "1.2.1"
slug: test_home
description: Vakio Test
url: "https://github.com/SergeyKupavtsev/test-home-assistant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world123..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
